kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kube-openmpi-run-data-claim
  namespace: openmpi
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi