sshKey:
  id_rsa: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAQEAokIWCBUjEtlsbrVrNGxD1c+l8aBrI6OqXmJzh/9pq9KBPYyLL3p6
    3r2ZAxIGWwBxP/237zEjpBu/V2VkTqILu+oJTntcEM4z+4b2zJvb5vD0BZfvbFDPAqDhQt
    YhGo8rvhTeOp46ZqSsF9EYekPXVio6v/HpUolMJhcYpma1Sjte+gR1qkHJhGLGa9yQBlPK
    YUj9jnu7T99b1wQbwEuIJ7vJ7NLDK1nKSKMKrsRsmUlJ6ks7tczlUxwN5SvW78oKuqeOIp
    22foss4RUEYR9Bq14v5Lm/LorkkzuuwlH3xDLe1IRRJqtEF7Q3EtaVrtgbPgloe5vDGz1S
    hrffvk1zEwAAA9joXYva6F2L2gAAAAdzc2gtcnNhAAABAQCiQhYIFSMS2WxutWs0bEPVz6
    XxoGsjo6peYnOH/2mr0oE9jIsvenrevZkDEgZbAHE//bfvMSOkG79XZWROogu76glOe1wQ
    zjP7hvbMm9vm8PQFl+9sUM8CoOFC1iEajyu+FN46njpmpKwX0Rh6Q9dWKjq/8elSiUwmFx
    imZrVKO176BHWqQcmEYsZr3JAGU8phSP2Oe7tP31vXBBvAS4gnu8ns0sMrWcpIowquxGyZ
    SUnqSzu1zOVTHA3lK9bvygq6p44inbZ+iyzhFQRhH0GrXi/kub8uiuSTO67CUffEMt7UhF
    Emq0QXtDcS1pWu2Bs+CWh7m8MbPVKGt9++TXMTAAAAAwEAAQAAAQBbzHPWgs7jHSuhvvY2
    JIKEdwR1ncK/2RrMZ3rhmHlagrAn+FnOtMbLOg1VlV8PIULxZ0QnCXAWqrQoZ+7GJhvpZt
    F5G4XM5Dy4s3Tx8cQJ9oy4lWsZpuZXoFmRjMAR3Kps0jWgiGCWLdhHaT8l/TfZQe8XJXBS
    B+eTLUH+8uDia6n+CgfRFV6EKv9jxgohRPUSQiLAgWHFgcCnkSMcyHJg8s3fzgLVbBDe0t
    wXffeLVyLrzWBeFzKS1Znon2qYMh/nxDpJbaIStltJsKsbT9JAfjSAlzamnaTyBYXUUExl
    07nKqvXgRSWN0RsJ2SPHc7t+wLhnson5rbKW+szrHNYRAAAAgFb7F8MBbZs6hDtRYKXqMk
    VrPycgtxoZlsugto82AqQOKc8QA2n5fn1olCF52KQS2wuhtJDEhh9hq7UIpSnIm8NqDVv6
    3Uidi4sUR578d3XgfolmwuF4EqC2e4HG3l0rj1J1o/jRA5PCfGMB5Vx/mDN6faFKq7nkCt
    GRdgwAIii3AAAAgQDO4YURMfqXvQawPwllbdZv463PKv3I6UfaeAqUaWL1FeP0+HPljaZG
    O5RQlHZUiBWOHNETjXfpnYYIfMaLfnQNcaDWM05qgPD2dI5P/uL1dUWQHFgwFBXn7bkPMX
    39OoEK/T8g4nEvoqdGrLrTqjwJ4MTVkSkifbyj94KojnqnVwAAAIEAyMhWemsDdySnoyEX
    ZV7RIPD4QkTO3TZHQwBthG0oSzMPCJFAl7FKI7AEJKYB7oWCH7rcZ6BKmDCJqD0fsLf2ay
    JqhxFuggymo/RV2AYxp3iVAZyxNoWDlfQNEhUn/G3FxRqxbnBPovTmp8WtajfQ1pdN8ShR
    coGjj5TtzCt2KKUAAAAfa2lra29tZXBAbWVwcy1NYWNCb29rLVByby5sb2NhbAECAwQ=
    -----END OPENSSH PRIVATE KEY-----

  id_rsa_pub: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiQhYIFSMS2WxutWs0bEPVz6XxoGsjo6peYnOH/2mr0oE9jIsvenrevZkDEgZbAHE//bfvMSOkG79XZWROogu76glOe1wQzjP7hvbMm9vm8PQFl+9sUM8CoOFC1iEajyu+FN46njpmpKwX0Rh6Q9dWKjq/8elSiUwmFximZrVKO176BHWqQcmEYsZr3JAGU8phSP2Oe7tP31vXBBvAS4gnu8ns0sMrWcpIowquxGyZSUnqSzu1zOVTHA3lK9bvygq6p44inbZ+iyzhFQRhH0GrXi/kub8uiuSTO67CUffEMt7UhFEmq0QXtDcS1pWu2Bs+CWh7m8MbPVKGt9++TXMT kikkomep@meps-MacBook-Pro.local
