# Minimalistic configuration example
global:
  timespan:
    start:
      year: "2019"
      month: "8"
      day: "25"
      hour: "0"
    end:
      year: "2019"
      month: "8"
      day: "25"
      hour: "6"

  geometry:
    ref_lat: 40.21
    ref_lon:  9.00
    truelat1: 38.00
    truelat2: 42.00
    stand_lon: 9.00
    map_proj: 'lambert'
    geog_data_path: '/geo/'
    geog_name: "geog_low_res_mandatory"
    request_resolution: "1p00"    
    gfs_data: "/gfs/model_data"
  real:
    # number of vertical levels in WPS
    # output (type ncdump -h on one of
    # the met_em* files to find out this
    # number)
    num_metgrid_levels: 34
    num_metgrid_soil_levels: 4
    auto_levels_opt: 1

  running:
    processes: 8
    processes_per_worker: 4
    input:
      interval_seconds: 10800
    time_step: 60.0
    history:
      outname: /run/data/wrfout_d<domain>_<date>.nc
    skip:
      prepare_wd: true
      geo_fetch: true
      gfs_fetch: true
      finalize: true
  physics:
    num_soil_layers: 4
    num_land_cat: 21  

domains:
  base:
    # timespan:
    #   start:
    #     year: "2019"
    #     month: "8"
    #     day: "17"
    #     hour: "0"
    #   end:
    #     year: "2019"
    #     month: "8"
    #     day: "17"
    #     hour: "6"
    geometry:
      geog_data_res: 'lowres'
#      geog_data_res: '2deg+gtopo_10m+usgs_10m+10m+nesdis_greenfrac'
      dx: 12000
      dy: 12000
      e_we: 51
      e_sn: 101
    running:
      history:
        interval: 60 # mins
        
  # a nested domain
  sardinia:
    parent: base
    geometry:
      parent_grid_ratio: 3
      i_parent_start: 13
      j_parent_start: 25
      e_we: 31
      e_sn: 61
    running:
      parent_time_step_ratio: 3

persistence:
  createPVC: false
  enable_writer: true
  config_data:
    path: "/data/config"
  init_data: 
    path: "/data/init"
    storage: 10Mi
  log_data:
    path: "/data/log"
    storage: 10Mi
    log_level: INFO
  run_data:
    path: "/data/run"
    storage: 10Mi
  out_data:
    path: "/data/out"
    variables: 'P'
    attributes: ''
    #storage: 10Mi # ignore when HDFS is enabled
    hdfs:
      user: "root"
      base_dir: "/wrf/simulations"
      namenode_uri: "hdfs://172.30.10.95:30820"
      configMap: "tailored-parrot-hdfs-config"
      
