
{{ if not .Values.global.running.skip.geo_fetch }}

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-wrf-init-job-1b-geo-fetch"
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-wrf-init-job-1b-geo-fetch"
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      volumes:
        - name: config-data
          configMap:
            name: {{ .Release.Name }}-config-data
        - name: init-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-init-data-claim
        - name: run-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-run-data-claim
      #initContainers:        
      containers:
        # - name: shell
        #   image: "{{ .Values.mpiDataWriterImage.repository }}:{{ .Values.mpiDataWriterImage.tag }}"
        #   imagePullPolicy: "{{ .Values.mpiDataWriterImage.pullPolicy }}"
        #   command: ["/bin/sleep","{{default "3600" .Values.sleepyTime}}"]
        #   volumeMounts:
        #     - name: config-data
        #       mountPath: {{ .Values.persistence.config_data.path }}
        #     - name: init-data
        #       mountPath: {{ .Values.persistence.init_data.path }}
        #     - name: run-data
        #       mountPath: {{ .Values.persistence.run_data.path }}
        - name: wrf-populate
          image: "{{ .Values.wrfInitializerImage.repository }}:{{ .Values.wrfInitializerImage.tag }}"
          imagePullPolicy: "{{ .Values.wrfInitializerImage.pullPolicy }}"
          #command: ["/bin/sleep","{{default "5" .Values.sleepyTime}}"]
          args: [
            "populate",
            "{{ .Values.global.geometry.geog_name }}",
            "{{ .Values.persistence.init_data.path }}{{ .Values.global.geometry.geog_data_path }}"
          ]
          volumeMounts:
            - name: config-data
              mountPath: {{ .Values.persistence.config_data.path }}
            - name: init-data
              mountPath: {{ .Values.persistence.init_data.path }}
            - name: run-data
              mountPath: {{ .Values.persistence.run_data.path }}        
      restartPolicy: OnFailure

{{ end }}